### ISSUE TITLE
错误反馈， The value of "offset" is out of range

### ISSUE THREAD

**Issue by zxcvbnm3057** [maotoumao/wxpc-miniprogram-decryption#1]
使用此脚本解密后，反编译报错：
'''
Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  9865
  dataLength:  2706001
  lastMark: 0xed

File list info:
  fileCount:  272
internal/buffer.js:72
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9861. Received 251659266
'''

使用[go语言版本](https://github.com/BlackTrace/pc_wxapkg_decrypt)解密后反编译正常

解密前小程序包[zipfile](https://github.com/xuedingmiaojun/wxappUnpacker/files/6340665/__APP__.zip)

**Comment by maotoumao** [comment]
emmm不好意思才看到 尴尬😅😅

**Comment by zxcvbnm3057** [comment]
没关系，已经搞定了
